spring:
  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog_db?serverTimezone=GMT
    username: root
    password: password
  jpa:
    show-sql: true
    # properties:
      # hibernate.enable_lazy_load_no_trans: true
server:
  port: 8081

custom:
  # 菜单根节点id
  menu:
    root.id: 1
